// Curated cities for sitemap, popular cities, and direct slug matching.
// Any city not in this list is geocoded dynamically via Open-Meteo.

export interface CityData {
  name: string;
  country: string;
  countryCode: string;
  latitude: number;
  longitude: number;
  timezone: string;
  region?: string; // For grouping in UI
}

// ~500 most-searched cities globally
export const CITIES: Record<string, CityData> = {
  // ═══════════════════════════════════════════════════════════════════
  // NORTH AMERICA (~80)
  // ═══════════════════════════════════════════════════════════════════

  // United States — Major cities
  "new-york": { name: "New York", country: "United States", countryCode: "US", latitude: 40.7128, longitude: -74.006, timezone: "America/New_York", region: "north-america" },
  "los-angeles": { name: "Los Angeles", country: "United States", countryCode: "US", latitude: 34.0522, longitude: -118.2437, timezone: "America/Los_Angeles", region: "north-america" },
  "chicago": { name: "Chicago", country: "United States", countryCode: "US", latitude: 41.8781, longitude: -87.6298, timezone: "America/Chicago", region: "north-america" },
  "houston": { name: "Houston", country: "United States", countryCode: "US", latitude: 29.7604, longitude: -95.3698, timezone: "America/Chicago", region: "north-america" },
  "phoenix": { name: "Phoenix", country: "United States", countryCode: "US", latitude: 33.4484, longitude: -112.074, timezone: "America/Phoenix", region: "north-america" },
  "philadelphia": { name: "Philadelphia", country: "United States", countryCode: "US", latitude: 39.9526, longitude: -75.1652, timezone: "America/New_York", region: "north-america" },
  "san-antonio": { name: "San Antonio", country: "United States", countryCode: "US", latitude: 29.4241, longitude: -98.4936, timezone: "America/Chicago", region: "north-america" },
  "san-diego": { name: "San Diego", country: "United States", countryCode: "US", latitude: 32.7157, longitude: -117.1611, timezone: "America/Los_Angeles", region: "north-america" },
  "dallas": { name: "Dallas", country: "United States", countryCode: "US", latitude: 32.7767, longitude: -96.797, timezone: "America/Chicago", region: "north-america" },
  "san-jose": { name: "San Jose", country: "United States", countryCode: "US", latitude: 37.3382, longitude: -121.8863, timezone: "America/Los_Angeles", region: "north-america" },
  "austin": { name: "Austin", country: "United States", countryCode: "US", latitude: 30.2672, longitude: -97.7431, timezone: "America/Chicago", region: "north-america" },
  "jacksonville": { name: "Jacksonville", country: "United States", countryCode: "US", latitude: 30.3322, longitude: -81.6557, timezone: "America/New_York", region: "north-america" },
  "san-francisco": { name: "San Francisco", country: "United States", countryCode: "US", latitude: 37.7749, longitude: -122.4194, timezone: "America/Los_Angeles", region: "north-america" },
  "seattle": { name: "Seattle", country: "United States", countryCode: "US", latitude: 47.6062, longitude: -122.3321, timezone: "America/Los_Angeles", region: "north-america" },
  "denver": { name: "Denver", country: "United States", countryCode: "US", latitude: 39.7392, longitude: -104.9903, timezone: "America/Denver", region: "north-america" },
  "washington-dc": { name: "Washington D.C.", country: "United States", countryCode: "US", latitude: 38.9072, longitude: -77.0369, timezone: "America/New_York", region: "north-america" },
  "nashville": { name: "Nashville", country: "United States", countryCode: "US", latitude: 36.1627, longitude: -86.7816, timezone: "America/Chicago", region: "north-america" },
  "miami": { name: "Miami", country: "United States", countryCode: "US", latitude: 25.7617, longitude: -80.1918, timezone: "America/New_York", region: "north-america" },
  "atlanta": { name: "Atlanta", country: "United States", countryCode: "US", latitude: 33.749, longitude: -84.388, timezone: "America/New_York", region: "north-america" },
  "boston": { name: "Boston", country: "United States", countryCode: "US", latitude: 42.3601, longitude: -71.0589, timezone: "America/New_York", region: "north-america" },
  "las-vegas": { name: "Las Vegas", country: "United States", countryCode: "US", latitude: 36.1699, longitude: -115.1398, timezone: "America/Los_Angeles", region: "north-america" },
  "portland": { name: "Portland", country: "United States", countryCode: "US", latitude: 45.5152, longitude: -122.6784, timezone: "America/Los_Angeles", region: "north-america" },
  "detroit": { name: "Detroit", country: "United States", countryCode: "US", latitude: 42.3314, longitude: -83.0458, timezone: "America/Detroit", region: "north-america" },
  "minneapolis": { name: "Minneapolis", country: "United States", countryCode: "US", latitude: 44.9778, longitude: -93.265, timezone: "America/Chicago", region: "north-america" },
  "orlando": { name: "Orlando", country: "United States", countryCode: "US", latitude: 28.5383, longitude: -81.3792, timezone: "America/New_York", region: "north-america" },
  "tampa": { name: "Tampa", country: "United States", countryCode: "US", latitude: 27.9506, longitude: -82.4572, timezone: "America/New_York", region: "north-america" },
  "charlotte": { name: "Charlotte", country: "United States", countryCode: "US", latitude: 35.2271, longitude: -80.8431, timezone: "America/New_York", region: "north-america" },
  "honolulu": { name: "Honolulu", country: "United States", countryCode: "US", latitude: 21.3069, longitude: -157.8583, timezone: "Pacific/Honolulu", region: "north-america" },
  "anchorage": { name: "Anchorage", country: "United States", countryCode: "US", latitude: 61.2181, longitude: -149.9003, timezone: "America/Anchorage", region: "north-america" },
  "salt-lake-city": { name: "Salt Lake City", country: "United States", countryCode: "US", latitude: 40.7608, longitude: -111.891, timezone: "America/Denver", region: "north-america" },
  "pittsburgh": { name: "Pittsburgh", country: "United States", countryCode: "US", latitude: 40.4406, longitude: -79.9959, timezone: "America/New_York", region: "north-america" },
  "st-louis": { name: "St. Louis", country: "United States", countryCode: "US", latitude: 38.627, longitude: -90.1994, timezone: "America/Chicago", region: "north-america" },
  "kansas-city": { name: "Kansas City", country: "United States", countryCode: "US", latitude: 39.0997, longitude: -94.5786, timezone: "America/Chicago", region: "north-america" },
  "raleigh": { name: "Raleigh", country: "United States", countryCode: "US", latitude: 35.7796, longitude: -78.6382, timezone: "America/New_York", region: "north-america" },
  "indianapolis": { name: "Indianapolis", country: "United States", countryCode: "US", latitude: 39.7684, longitude: -86.1581, timezone: "America/Indiana/Indianapolis", region: "north-america" },
  "new-orleans": { name: "New Orleans", country: "United States", countryCode: "US", latitude: 29.9511, longitude: -90.0715, timezone: "America/Chicago", region: "north-america" },
  // United States — Additional state capitals & major cities
  "sacramento": { name: "Sacramento", country: "United States", countryCode: "US", latitude: 38.5816, longitude: -121.4944, timezone: "America/Los_Angeles", region: "north-america" },
  "columbus": { name: "Columbus", country: "United States", countryCode: "US", latitude: 39.9612, longitude: -82.9988, timezone: "America/New_York", region: "north-america" },
  "richmond": { name: "Richmond", country: "United States", countryCode: "US", latitude: 37.5407, longitude: -77.4360, timezone: "America/New_York", region: "north-america" },
  "hartford": { name: "Hartford", country: "United States", countryCode: "US", latitude: 41.7658, longitude: -72.6734, timezone: "America/New_York", region: "north-america" },
  "madison": { name: "Madison", country: "United States", countryCode: "US", latitude: 43.0731, longitude: -89.4012, timezone: "America/Chicago", region: "north-america" },
  "baton-rouge": { name: "Baton Rouge", country: "United States", countryCode: "US", latitude: 30.4515, longitude: -91.1871, timezone: "America/Chicago", region: "north-america" },
  "montgomery": { name: "Montgomery", country: "United States", countryCode: "US", latitude: 32.3792, longitude: -86.3077, timezone: "America/Chicago", region: "north-america" },
  "little-rock": { name: "Little Rock", country: "United States", countryCode: "US", latitude: 34.7465, longitude: -92.2896, timezone: "America/Chicago", region: "north-america" },
  "des-moines": { name: "Des Moines", country: "United States", countryCode: "US", latitude: 41.5868, longitude: -93.6250, timezone: "America/Chicago", region: "north-america" },
  "oklahoma-city": { name: "Oklahoma City", country: "United States", countryCode: "US", latitude: 35.4676, longitude: -97.5164, timezone: "America/Chicago", region: "north-america" },
  "albuquerque": { name: "Albuquerque", country: "United States", countryCode: "US", latitude: 35.0844, longitude: -106.6504, timezone: "America/Denver", region: "north-america" },
  "boise": { name: "Boise", country: "United States", countryCode: "US", latitude: 43.6150, longitude: -116.2023, timezone: "America/Boise", region: "north-america" },
  "charleston": { name: "Charleston", country: "United States", countryCode: "US", latitude: 32.7765, longitude: -79.9311, timezone: "America/New_York", region: "north-america" },
  "milwaukee": { name: "Milwaukee", country: "United States", countryCode: "US", latitude: 43.0389, longitude: -87.9065, timezone: "America/Chicago", region: "north-america" },
  "memphis": { name: "Memphis", country: "United States", countryCode: "US", latitude: 35.1495, longitude: -90.0490, timezone: "America/Chicago", region: "north-america" },
  "baltimore": { name: "Baltimore", country: "United States", countryCode: "US", latitude: 39.2904, longitude: -76.6122, timezone: "America/New_York", region: "north-america" },
  "louisville": { name: "Louisville", country: "United States", countryCode: "US", latitude: 38.2527, longitude: -85.7585, timezone: "America/Kentucky/Louisville", region: "north-america" },
  "tucson": { name: "Tucson", country: "United States", countryCode: "US", latitude: 32.2226, longitude: -110.9747, timezone: "America/Phoenix", region: "north-america" },
  "el-paso": { name: "El Paso", country: "United States", countryCode: "US", latitude: 31.7619, longitude: -106.4850, timezone: "America/Denver", region: "north-america" },
  "buffalo": { name: "Buffalo", country: "United States", countryCode: "US", latitude: 42.8864, longitude: -78.8784, timezone: "America/New_York", region: "north-america" },
  "providence": { name: "Providence", country: "United States", countryCode: "US", latitude: 41.8240, longitude: -71.4128, timezone: "America/New_York", region: "north-america" },
  "birmingham-al": { name: "Birmingham", country: "United States", countryCode: "US", latitude: 33.5207, longitude: -86.8025, timezone: "America/Chicago", region: "north-america" },
  "omaha": { name: "Omaha", country: "United States", countryCode: "US", latitude: 41.2565, longitude: -95.9345, timezone: "America/Chicago", region: "north-america" },
  "wichita": { name: "Wichita", country: "United States", countryCode: "US", latitude: 37.6872, longitude: -97.3301, timezone: "America/Chicago", region: "north-america" },
  "fresno": { name: "Fresno", country: "United States", countryCode: "US", latitude: 36.7378, longitude: -119.7871, timezone: "America/Los_Angeles", region: "north-america" },
  "colorado-springs": { name: "Colorado Springs", country: "United States", countryCode: "US", latitude: 38.8339, longitude: -104.8214, timezone: "America/Denver", region: "north-america" },
  "virginia-beach": { name: "Virginia Beach", country: "United States", countryCode: "US", latitude: 36.8529, longitude: -75.9780, timezone: "America/New_York", region: "north-america" },
  "savannah": { name: "Savannah", country: "United States", countryCode: "US", latitude: 32.0809, longitude: -81.0912, timezone: "America/New_York", region: "north-america" },
  "fort-worth": { name: "Fort Worth", country: "United States", countryCode: "US", latitude: 32.7555, longitude: -97.3308, timezone: "America/Chicago", region: "north-america" },
  "cleveland": { name: "Cleveland", country: "United States", countryCode: "US", latitude: 41.4993, longitude: -81.6944, timezone: "America/New_York", region: "north-america" },
  "cincinnati": { name: "Cincinnati", country: "United States", countryCode: "US", latitude: 39.1031, longitude: -84.5120, timezone: "America/New_York", region: "north-america" },
  "tulsa": { name: "Tulsa", country: "United States", countryCode: "US", latitude: 36.1540, longitude: -95.9928, timezone: "America/Chicago", region: "north-america" },
  "reno": { name: "Reno", country: "United States", countryCode: "US", latitude: 39.5296, longitude: -119.8138, timezone: "America/Los_Angeles", region: "north-america" },
  "spokane": { name: "Spokane", country: "United States", countryCode: "US", latitude: 47.6588, longitude: -117.4260, timezone: "America/Los_Angeles", region: "north-america" },
  "santa-fe": { name: "Santa Fe", country: "United States", countryCode: "US", latitude: 35.6870, longitude: -105.9378, timezone: "America/Denver", region: "north-america" },
  "pensacola": { name: "Pensacola", country: "United States", countryCode: "US", latitude: 30.4213, longitude: -87.2169, timezone: "America/Chicago", region: "north-america" },
  "fort-lauderdale": { name: "Fort Lauderdale", country: "United States", countryCode: "US", latitude: 26.1224, longitude: -80.1373, timezone: "America/New_York", region: "north-america" },
  "myrtle-beach": { name: "Myrtle Beach", country: "United States", countryCode: "US", latitude: 33.6891, longitude: -78.8867, timezone: "America/New_York", region: "north-america" },
  // Canada
  "toronto": { name: "Toronto", country: "Canada", countryCode: "CA", latitude: 43.6532, longitude: -79.3832, timezone: "America/Toronto", region: "north-america" },
  "vancouver": { name: "Vancouver", country: "Canada", countryCode: "CA", latitude: 49.2827, longitude: -123.1207, timezone: "America/Vancouver", region: "north-america" },
  "montreal": { name: "Montreal", country: "Canada", countryCode: "CA", latitude: 45.5017, longitude: -73.5673, timezone: "America/Toronto", region: "north-america" },
  "calgary": { name: "Calgary", country: "Canada", countryCode: "CA", latitude: 51.0447, longitude: -114.0719, timezone: "America/Edmonton", region: "north-america" },
  "ottawa": { name: "Ottawa", country: "Canada", countryCode: "CA", latitude: 45.4215, longitude: -75.6972, timezone: "America/Toronto", region: "north-america" },
  "edmonton": { name: "Edmonton", country: "Canada", countryCode: "CA", latitude: 53.5461, longitude: -113.4938, timezone: "America/Edmonton", region: "north-america" },
  "winnipeg": { name: "Winnipeg", country: "Canada", countryCode: "CA", latitude: 49.8951, longitude: -97.1384, timezone: "America/Winnipeg", region: "north-america" },
  "quebec-city": { name: "Quebec City", country: "Canada", countryCode: "CA", latitude: 46.8139, longitude: -71.2080, timezone: "America/Toronto", region: "north-america" },
  "halifax": { name: "Halifax", country: "Canada", countryCode: "CA", latitude: 44.6488, longitude: -63.5752, timezone: "America/Halifax", region: "north-america" },
  "victoria": { name: "Victoria", country: "Canada", countryCode: "CA", latitude: 48.4284, longitude: -123.3656, timezone: "America/Vancouver", region: "north-america" },
  "saskatoon": { name: "Saskatoon", country: "Canada", countryCode: "CA", latitude: 52.1332, longitude: -106.6700, timezone: "America/Regina", region: "north-america" },
  "kelowna": { name: "Kelowna", country: "Canada", countryCode: "CA", latitude: 49.8880, longitude: -119.4960, timezone: "America/Vancouver", region: "north-america" },

  // ═══════════════════════════════════════════════════════════════════
  // EUROPE (~120)
  // ═══════════════════════════════════════════════════════════════════

  // United Kingdom
  "london": { name: "London", country: "United Kingdom", countryCode: "GB", latitude: 51.5074, longitude: -0.1278, timezone: "Europe/London", region: "europe" },
  "edinburgh": { name: "Edinburgh", country: "United Kingdom", countryCode: "GB", latitude: 55.9533, longitude: -3.1883, timezone: "Europe/London", region: "europe" },
  "manchester": { name: "Manchester", country: "United Kingdom", countryCode: "GB", latitude: 53.4808, longitude: -2.2426, timezone: "Europe/London", region: "europe" },
  "birmingham": { name: "Birmingham", country: "United Kingdom", countryCode: "GB", latitude: 52.4862, longitude: -1.8904, timezone: "Europe/London", region: "europe" },
  "glasgow": { name: "Glasgow", country: "United Kingdom", countryCode: "GB", latitude: 55.8642, longitude: -4.2518, timezone: "Europe/London", region: "europe" },
  "liverpool": { name: "Liverpool", country: "United Kingdom", countryCode: "GB", latitude: 53.4084, longitude: -2.9916, timezone: "Europe/London", region: "europe" },
  "bristol": { name: "Bristol", country: "United Kingdom", countryCode: "GB", latitude: 51.4545, longitude: -2.5879, timezone: "Europe/London", region: "europe" },
  "leeds": { name: "Leeds", country: "United Kingdom", countryCode: "GB", latitude: 53.8008, longitude: -1.5491, timezone: "Europe/London", region: "europe" },
  "cardiff": { name: "Cardiff", country: "United Kingdom", countryCode: "GB", latitude: 51.4816, longitude: -3.1791, timezone: "Europe/London", region: "europe" },
  "belfast": { name: "Belfast", country: "United Kingdom", countryCode: "GB", latitude: 54.5973, longitude: -5.9301, timezone: "Europe/London", region: "europe" },
  // France
  "paris": { name: "Paris", country: "France", countryCode: "FR", latitude: 48.8566, longitude: 2.3522, timezone: "Europe/Paris", region: "europe" },
  "lyon": { name: "Lyon", country: "France", countryCode: "FR", latitude: 45.764, longitude: 4.8357, timezone: "Europe/Paris", region: "europe" },
  "marseille": { name: "Marseille", country: "France", countryCode: "FR", latitude: 43.2965, longitude: 5.3698, timezone: "Europe/Paris", region: "europe" },
  "nice": { name: "Nice", country: "France", countryCode: "FR", latitude: 43.7102, longitude: 7.2620, timezone: "Europe/Paris", region: "europe" },
  "toulouse": { name: "Toulouse", country: "France", countryCode: "FR", latitude: 43.6047, longitude: 1.4442, timezone: "Europe/Paris", region: "europe" },
  "bordeaux": { name: "Bordeaux", country: "France", countryCode: "FR", latitude: 44.8378, longitude: -0.5792, timezone: "Europe/Paris", region: "europe" },
  "strasbourg": { name: "Strasbourg", country: "France", countryCode: "FR", latitude: 48.5734, longitude: 7.7521, timezone: "Europe/Paris", region: "europe" },
  // Germany
  "berlin": { name: "Berlin", country: "Germany", countryCode: "DE", latitude: 52.52, longitude: 13.405, timezone: "Europe/Berlin", region: "europe" },
  "munich": { name: "Munich", country: "Germany", countryCode: "DE", latitude: 48.1351, longitude: 11.582, timezone: "Europe/Berlin", region: "europe" },
  "hamburg": { name: "Hamburg", country: "Germany", countryCode: "DE", latitude: 53.5511, longitude: 9.9937, timezone: "Europe/Berlin", region: "europe" },
  "frankfurt": { name: "Frankfurt", country: "Germany", countryCode: "DE", latitude: 50.1109, longitude: 8.6821, timezone: "Europe/Berlin", region: "europe" },
  "cologne": { name: "Cologne", country: "Germany", countryCode: "DE", latitude: 50.9375, longitude: 6.9603, timezone: "Europe/Berlin", region: "europe" },
  "dusseldorf": { name: "Düsseldorf", country: "Germany", countryCode: "DE", latitude: 51.2277, longitude: 6.7735, timezone: "Europe/Berlin", region: "europe" },
  "stuttgart": { name: "Stuttgart", country: "Germany", countryCode: "DE", latitude: 48.7758, longitude: 9.1829, timezone: "Europe/Berlin", region: "europe" },
  "dresden": { name: "Dresden", country: "Germany", countryCode: "DE", latitude: 51.0504, longitude: 13.7373, timezone: "Europe/Berlin", region: "europe" },
  // Spain
  "madrid": { name: "Madrid", country: "Spain", countryCode: "ES", latitude: 40.4168, longitude: -3.7038, timezone: "Europe/Madrid", region: "europe" },
  "barcelona": { name: "Barcelona", country: "Spain", countryCode: "ES", latitude: 41.3874, longitude: 2.1686, timezone: "Europe/Madrid", region: "europe" },
  "seville": { name: "Seville", country: "Spain", countryCode: "ES", latitude: 37.3891, longitude: -5.9845, timezone: "Europe/Madrid", region: "europe" },
  "valencia": { name: "Valencia", country: "Spain", countryCode: "ES", latitude: 39.4699, longitude: -0.3763, timezone: "Europe/Madrid", region: "europe" },
  "malaga": { name: "Málaga", country: "Spain", countryCode: "ES", latitude: 36.7213, longitude: -4.4214, timezone: "Europe/Madrid", region: "europe" },
  "bilbao": { name: "Bilbao", country: "Spain", countryCode: "ES", latitude: 43.2630, longitude: -2.9350, timezone: "Europe/Madrid", region: "europe" },
  "palma-de-mallorca": { name: "Palma de Mallorca", country: "Spain", countryCode: "ES", latitude: 39.5696, longitude: 2.6502, timezone: "Europe/Madrid", region: "europe" },
  // Italy
  "rome": { name: "Rome", country: "Italy", countryCode: "IT", latitude: 41.9028, longitude: 12.4964, timezone: "Europe/Rome", region: "europe" },
  "milan": { name: "Milan", country: "Italy", countryCode: "IT", latitude: 45.4642, longitude: 9.19, timezone: "Europe/Rome", region: "europe" },
  "naples": { name: "Naples", country: "Italy", countryCode: "IT", latitude: 40.8518, longitude: 14.2681, timezone: "Europe/Rome", region: "europe" },
  "florence": { name: "Florence", country: "Italy", countryCode: "IT", latitude: 43.7696, longitude: 11.2558, timezone: "Europe/Rome", region: "europe" },
  "venice": { name: "Venice", country: "Italy", countryCode: "IT", latitude: 45.4408, longitude: 12.3155, timezone: "Europe/Rome", region: "europe" },
  "turin": { name: "Turin", country: "Italy", countryCode: "IT", latitude: 45.0703, longitude: 7.6869, timezone: "Europe/Rome", region: "europe" },
  "bologna": { name: "Bologna", country: "Italy", countryCode: "IT", latitude: 44.4949, longitude: 11.3426, timezone: "Europe/Rome", region: "europe" },
  "palermo": { name: "Palermo", country: "Italy", countryCode: "IT", latitude: 38.1157, longitude: 13.3615, timezone: "Europe/Rome", region: "europe" },
  // Netherlands, Belgium, Luxembourg
  "amsterdam": { name: "Amsterdam", country: "Netherlands", countryCode: "NL", latitude: 52.3676, longitude: 4.9041, timezone: "Europe/Amsterdam", region: "europe" },
  "rotterdam": { name: "Rotterdam", country: "Netherlands", countryCode: "NL", latitude: 51.9244, longitude: 4.4777, timezone: "Europe/Amsterdam", region: "europe" },
  "the-hague": { name: "The Hague", country: "Netherlands", countryCode: "NL", latitude: 52.0705, longitude: 4.3007, timezone: "Europe/Amsterdam", region: "europe" },
  "brussels": { name: "Brussels", country: "Belgium", countryCode: "BE", latitude: 50.8503, longitude: 4.3517, timezone: "Europe/Brussels", region: "europe" },
  "antwerp": { name: "Antwerp", country: "Belgium", countryCode: "BE", latitude: 51.2194, longitude: 4.4025, timezone: "Europe/Brussels", region: "europe" },
  "luxembourg-city": { name: "Luxembourg City", country: "Luxembourg", countryCode: "LU", latitude: 49.6117, longitude: 6.1300, timezone: "Europe/Luxembourg", region: "europe" },
  // Portugal
  "lisbon": { name: "Lisbon", country: "Portugal", countryCode: "PT", latitude: 38.7223, longitude: -9.1393, timezone: "Europe/Lisbon", region: "europe" },
  "porto": { name: "Porto", country: "Portugal", countryCode: "PT", latitude: 41.1579, longitude: -8.6291, timezone: "Europe/Lisbon", region: "europe" },
  // Austria, Switzerland
  "vienna": { name: "Vienna", country: "Austria", countryCode: "AT", latitude: 48.2082, longitude: 16.3738, timezone: "Europe/Vienna", region: "europe" },
  "salzburg": { name: "Salzburg", country: "Austria", countryCode: "AT", latitude: 47.8095, longitude: 13.0550, timezone: "Europe/Vienna", region: "europe" },
  "innsbruck": { name: "Innsbruck", country: "Austria", countryCode: "AT", latitude: 47.2692, longitude: 11.4041, timezone: "Europe/Vienna", region: "europe" },
  "zurich": { name: "Zurich", country: "Switzerland", countryCode: "CH", latitude: 47.3769, longitude: 8.5417, timezone: "Europe/Zurich", region: "europe" },
  "geneva": { name: "Geneva", country: "Switzerland", countryCode: "CH", latitude: 46.2044, longitude: 6.1432, timezone: "Europe/Zurich", region: "europe" },
  "bern": { name: "Bern", country: "Switzerland", countryCode: "CH", latitude: 46.9480, longitude: 7.4474, timezone: "Europe/Zurich", region: "europe" },
  // Scandinavia
  "stockholm": { name: "Stockholm", country: "Sweden", countryCode: "SE", latitude: 59.3293, longitude: 18.0686, timezone: "Europe/Stockholm", region: "europe" },
  "gothenburg": { name: "Gothenburg", country: "Sweden", countryCode: "SE", latitude: 57.7089, longitude: 11.9746, timezone: "Europe/Stockholm", region: "europe" },
  "oslo": { name: "Oslo", country: "Norway", countryCode: "NO", latitude: 59.9139, longitude: 10.7522, timezone: "Europe/Oslo", region: "europe" },
  "bergen": { name: "Bergen", country: "Norway", countryCode: "NO", latitude: 60.3913, longitude: 5.3221, timezone: "Europe/Oslo", region: "europe" },
  "copenhagen": { name: "Copenhagen", country: "Denmark", countryCode: "DK", latitude: 55.6761, longitude: 12.5683, timezone: "Europe/Copenhagen", region: "europe" },
  "helsinki": { name: "Helsinki", country: "Finland", countryCode: "FI", latitude: 60.1699, longitude: 24.9384, timezone: "Europe/Helsinki", region: "europe" },
  "reykjavik": { name: "Reykjavik", country: "Iceland", countryCode: "IS", latitude: 64.1466, longitude: -21.9426, timezone: "Atlantic/Reykjavik", region: "europe" },
  // Eastern Europe
  "warsaw": { name: "Warsaw", country: "Poland", countryCode: "PL", latitude: 52.2297, longitude: 21.0122, timezone: "Europe/Warsaw", region: "europe" },
  "krakow": { name: "Kraków", country: "Poland", countryCode: "PL", latitude: 50.0647, longitude: 19.9450, timezone: "Europe/Warsaw", region: "europe" },
  "gdansk": { name: "Gdańsk", country: "Poland", countryCode: "PL", latitude: 54.3520, longitude: 18.6466, timezone: "Europe/Warsaw", region: "europe" },
  "budapest": { name: "Budapest", country: "Hungary", countryCode: "HU", latitude: 47.4979, longitude: 19.0402, timezone: "Europe/Budapest", region: "europe" },
  "prague": { name: "Prague", country: "Czech Republic", countryCode: "CZ", latitude: 50.0755, longitude: 14.4378, timezone: "Europe/Prague", region: "europe" },
  "bratislava": { name: "Bratislava", country: "Slovakia", countryCode: "SK", latitude: 48.1486, longitude: 17.1077, timezone: "Europe/Bratislava", region: "europe" },
  "bucharest": { name: "Bucharest", country: "Romania", countryCode: "RO", latitude: 44.4268, longitude: 26.1025, timezone: "Europe/Bucharest", region: "europe" },
  "cluj-napoca": { name: "Cluj-Napoca", country: "Romania", countryCode: "RO", latitude: 46.7712, longitude: 23.6236, timezone: "Europe/Bucharest", region: "europe" },
  "sofia": { name: "Sofia", country: "Bulgaria", countryCode: "BG", latitude: 42.6977, longitude: 23.3219, timezone: "Europe/Sofia", region: "europe" },
  "kiev": { name: "Kyiv", country: "Ukraine", countryCode: "UA", latitude: 50.4501, longitude: 30.5234, timezone: "Europe/Kyiv", region: "europe" },
  "lviv": { name: "Lviv", country: "Ukraine", countryCode: "UA", latitude: 49.8397, longitude: 24.0297, timezone: "Europe/Kyiv", region: "europe" },
  "minsk": { name: "Minsk", country: "Belarus", countryCode: "BY", latitude: 53.9006, longitude: 27.5590, timezone: "Europe/Minsk", region: "europe" },
  // Balkans & Greece
  "athens": { name: "Athens", country: "Greece", countryCode: "GR", latitude: 37.9838, longitude: 23.7275, timezone: "Europe/Athens", region: "europe" },
  "thessaloniki": { name: "Thessaloniki", country: "Greece", countryCode: "GR", latitude: 40.6401, longitude: 22.9444, timezone: "Europe/Athens", region: "europe" },
  "belgrade": { name: "Belgrade", country: "Serbia", countryCode: "RS", latitude: 44.7866, longitude: 20.4489, timezone: "Europe/Belgrade", region: "europe" },
  "zagreb": { name: "Zagreb", country: "Croatia", countryCode: "HR", latitude: 45.815, longitude: 15.9819, timezone: "Europe/Zagreb", region: "europe" },
  "dubrovnik": { name: "Dubrovnik", country: "Croatia", countryCode: "HR", latitude: 42.6507, longitude: 18.0944, timezone: "Europe/Zagreb", region: "europe" },
  "split": { name: "Split", country: "Croatia", countryCode: "HR", latitude: 43.5081, longitude: 16.4402, timezone: "Europe/Zagreb", region: "europe" },
  "ljubljana": { name: "Ljubljana", country: "Slovenia", countryCode: "SI", latitude: 46.0569, longitude: 14.5058, timezone: "Europe/Ljubljana", region: "europe" },
  "tirana": { name: "Tirana", country: "Albania", countryCode: "AL", latitude: 41.3275, longitude: 19.8187, timezone: "Europe/Tirane", region: "europe" },
  "skopje": { name: "Skopje", country: "North Macedonia", countryCode: "MK", latitude: 41.9973, longitude: 21.4280, timezone: "Europe/Skopje", region: "europe" },
  "sarajevo": { name: "Sarajevo", country: "Bosnia and Herzegovina", countryCode: "BA", latitude: 43.8563, longitude: 18.4131, timezone: "Europe/Sarajevo", region: "europe" },
  "podgorica": { name: "Podgorica", country: "Montenegro", countryCode: "ME", latitude: 42.4304, longitude: 19.2594, timezone: "Europe/Podgorica", region: "europe" },
  // Russia & Turkey
  "moscow": { name: "Moscow", country: "Russia", countryCode: "RU", latitude: 55.7558, longitude: 37.6173, timezone: "Europe/Moscow", region: "europe" },
  "st-petersburg": { name: "St. Petersburg", country: "Russia", countryCode: "RU", latitude: 59.9343, longitude: 30.3351, timezone: "Europe/Moscow", region: "europe" },
  "istanbul": { name: "Istanbul", country: "Turkey", countryCode: "TR", latitude: 41.0082, longitude: 28.9784, timezone: "Europe/Istanbul", region: "europe" },
  "ankara": { name: "Ankara", country: "Turkey", countryCode: "TR", latitude: 39.9334, longitude: 32.8597, timezone: "Europe/Istanbul", region: "europe" },
  "antalya": { name: "Antalya", country: "Turkey", countryCode: "TR", latitude: 36.8969, longitude: 30.7133, timezone: "Europe/Istanbul", region: "europe" },
  "izmir": { name: "İzmir", country: "Turkey", countryCode: "TR", latitude: 38.4237, longitude: 27.1428, timezone: "Europe/Istanbul", region: "europe" },
  // Ireland
  "dublin": { name: "Dublin", country: "Ireland", countryCode: "IE", latitude: 53.3498, longitude: -6.2603, timezone: "Europe/Dublin", region: "europe" },
  "cork": { name: "Cork", country: "Ireland", countryCode: "IE", latitude: 51.8969, longitude: -8.4863, timezone: "Europe/Dublin", region: "europe" },
  // Baltics
  "tallinn": { name: "Tallinn", country: "Estonia", countryCode: "EE", latitude: 59.4370, longitude: 24.7536, timezone: "Europe/Tallinn", region: "europe" },
  "riga": { name: "Riga", country: "Latvia", countryCode: "LV", latitude: 56.9496, longitude: 24.1052, timezone: "Europe/Riga", region: "europe" },
  "vilnius": { name: "Vilnius", country: "Lithuania", countryCode: "LT", latitude: 54.6872, longitude: 25.2797, timezone: "Europe/Vilnius", region: "europe" },
  // Malta, Cyprus
  "valletta": { name: "Valletta", country: "Malta", countryCode: "MT", latitude: 35.8989, longitude: 14.5146, timezone: "Europe/Malta", region: "europe" },
  "nicosia": { name: "Nicosia", country: "Cyprus", countryCode: "CY", latitude: 35.1856, longitude: 33.3823, timezone: "Asia/Nicosia", region: "europe" },
  // Additional European cities
  "genoa": { name: "Genoa", country: "Italy", countryCode: "IT", latitude: 44.4056, longitude: 8.9463, timezone: "Europe/Rome", region: "europe" },
  "catania": { name: "Catania", country: "Italy", countryCode: "IT", latitude: 37.5079, longitude: 15.0830, timezone: "Europe/Rome", region: "europe" },
  "granada": { name: "Granada", country: "Spain", countryCode: "ES", latitude: 37.1773, longitude: -3.5986, timezone: "Europe/Madrid", region: "europe" },
  "san-sebastian": { name: "San Sebastián", country: "Spain", countryCode: "ES", latitude: 43.3183, longitude: -1.9812, timezone: "Europe/Madrid", region: "europe" },
  "zaragoza": { name: "Zaragoza", country: "Spain", countryCode: "ES", latitude: 41.6488, longitude: -0.8891, timezone: "Europe/Madrid", region: "europe" },
  "nantes": { name: "Nantes", country: "France", countryCode: "FR", latitude: 47.2184, longitude: -1.5536, timezone: "Europe/Paris", region: "europe" },
  "lille": { name: "Lille", country: "France", countryCode: "FR", latitude: 50.6292, longitude: 3.0573, timezone: "Europe/Paris", region: "europe" },
  "montpellier": { name: "Montpellier", country: "France", countryCode: "FR", latitude: 43.6108, longitude: 3.8767, timezone: "Europe/Paris", region: "europe" },
  "hannover": { name: "Hannover", country: "Germany", countryCode: "DE", latitude: 52.3759, longitude: 9.7320, timezone: "Europe/Berlin", region: "europe" },
  "leipzig": { name: "Leipzig", country: "Germany", countryCode: "DE", latitude: 51.3397, longitude: 12.3731, timezone: "Europe/Berlin", region: "europe" },
  "nuremberg": { name: "Nuremberg", country: "Germany", countryCode: "DE", latitude: 49.4521, longitude: 11.0767, timezone: "Europe/Berlin", region: "europe" },
  "wroclaw": { name: "Wrocław", country: "Poland", countryCode: "PL", latitude: 51.1079, longitude: 17.0385, timezone: "Europe/Warsaw", region: "europe" },
  "poznan": { name: "Poznań", country: "Poland", countryCode: "PL", latitude: 52.4064, longitude: 16.9252, timezone: "Europe/Warsaw", region: "europe" },
  "faro": { name: "Faro", country: "Portugal", countryCode: "PT", latitude: 37.0194, longitude: -7.9322, timezone: "Europe/Lisbon", region: "europe" },
  "funchal": { name: "Funchal", country: "Portugal", countryCode: "PT", latitude: 32.6669, longitude: -16.9241, timezone: "Atlantic/Madeira", region: "europe" },
  "constanta": { name: "Constanța", country: "Romania", countryCode: "RO", latitude: 44.1598, longitude: 28.6348, timezone: "Europe/Bucharest", region: "europe" },
  "plovdiv": { name: "Plovdiv", country: "Bulgaria", countryCode: "BG", latitude: 42.1354, longitude: 24.7453, timezone: "Europe/Sofia", region: "europe" },
  "chisinau": { name: "Chișinău", country: "Moldova", countryCode: "MD", latitude: 47.0105, longitude: 28.8638, timezone: "Europe/Chisinau", region: "europe" },
  "kosice": { name: "Košice", country: "Slovakia", countryCode: "SK", latitude: 48.7164, longitude: 21.2611, timezone: "Europe/Bratislava", region: "europe" },
  "brno": { name: "Brno", country: "Czech Republic", countryCode: "CZ", latitude: 49.1951, longitude: 16.6068, timezone: "Europe/Prague", region: "europe" },
  "debrecen": { name: "Debrecen", country: "Hungary", countryCode: "HU", latitude: 47.5316, longitude: 21.6273, timezone: "Europe/Budapest", region: "europe" },
  "malmo": { name: "Malmö", country: "Sweden", countryCode: "SE", latitude: 55.6050, longitude: 13.0038, timezone: "Europe/Stockholm", region: "europe" },
  "turku": { name: "Turku", country: "Finland", countryCode: "FI", latitude: 60.4518, longitude: 22.2666, timezone: "Europe/Helsinki", region: "europe" },
  "aarhus": { name: "Aarhus", country: "Denmark", countryCode: "DK", latitude: 56.1629, longitude: 10.2039, timezone: "Europe/Copenhagen", region: "europe" },
  "tromsoe": { name: "Tromsø", country: "Norway", countryCode: "NO", latitude: 69.6492, longitude: 18.9553, timezone: "Europe/Oslo", region: "europe" },
  "odessa": { name: "Odesa", country: "Ukraine", countryCode: "UA", latitude: 46.4825, longitude: 30.7233, timezone: "Europe/Kyiv", region: "europe" },
  "santorini": { name: "Santorini", country: "Greece", countryCode: "GR", latitude: 36.3932, longitude: 25.4615, timezone: "Europe/Athens", region: "europe" },
  "heraklion": { name: "Heraklion", country: "Greece", countryCode: "GR", latitude: 35.3387, longitude: 25.1442, timezone: "Europe/Athens", region: "europe" },
  "bodrum": { name: "Bodrum", country: "Turkey", countryCode: "TR", latitude: 37.0344, longitude: 27.4305, timezone: "Europe/Istanbul", region: "europe" },
  "palma": { name: "Las Palmas", country: "Spain", countryCode: "ES", latitude: 28.1235, longitude: -15.4363, timezone: "Atlantic/Canary", region: "europe" },
  "tenerife": { name: "Santa Cruz de Tenerife", country: "Spain", countryCode: "ES", latitude: 28.4636, longitude: -16.2518, timezone: "Atlantic/Canary", region: "europe" },
  "bath": { name: "Bath", country: "United Kingdom", countryCode: "GB", latitude: 51.3811, longitude: -2.3590, timezone: "Europe/London", region: "europe" },
  "york": { name: "York", country: "United Kingdom", countryCode: "GB", latitude: 53.9591, longitude: -1.0815, timezone: "Europe/London", region: "europe" },
  "siena": { name: "Siena", country: "Italy", countryCode: "IT", latitude: 43.3188, longitude: 11.3308, timezone: "Europe/Rome", region: "europe" },
  "verona": { name: "Verona", country: "Italy", countryCode: "IT", latitude: 45.4384, longitude: 10.9917, timezone: "Europe/Rome", region: "europe" },
  "monaco": { name: "Monaco", country: "Monaco", countryCode: "MC", latitude: 43.7384, longitude: 7.4246, timezone: "Europe/Monaco", region: "europe" },
  "andorra-la-vella": { name: "Andorra la Vella", country: "Andorra", countryCode: "AD", latitude: 42.5063, longitude: 1.5218, timezone: "Europe/Andorra", region: "europe" },

  // ═══════════════════════════════════════════════════════════════════
  // ASIA (~130)
  // ═══════════════════════════════════════════════════════════════════

  // Japan
  "tokyo": { name: "Tokyo", country: "Japan", countryCode: "JP", latitude: 35.6762, longitude: 139.6503, timezone: "Asia/Tokyo", region: "asia" },
  "osaka": { name: "Osaka", country: "Japan", countryCode: "JP", latitude: 34.6937, longitude: 135.5023, timezone: "Asia/Tokyo", region: "asia" },
  "kyoto": { name: "Kyoto", country: "Japan", countryCode: "JP", latitude: 35.0116, longitude: 135.7681, timezone: "Asia/Tokyo", region: "asia" },
  "yokohama": { name: "Yokohama", country: "Japan", countryCode: "JP", latitude: 35.4437, longitude: 139.6380, timezone: "Asia/Tokyo", region: "asia" },
  "nagoya": { name: "Nagoya", country: "Japan", countryCode: "JP", latitude: 35.1815, longitude: 136.9066, timezone: "Asia/Tokyo", region: "asia" },
  "sapporo": { name: "Sapporo", country: "Japan", countryCode: "JP", latitude: 43.0618, longitude: 141.3545, timezone: "Asia/Tokyo", region: "asia" },
  "fukuoka": { name: "Fukuoka", country: "Japan", countryCode: "JP", latitude: 33.5904, longitude: 130.4017, timezone: "Asia/Tokyo", region: "asia" },
  "hiroshima": { name: "Hiroshima", country: "Japan", countryCode: "JP", latitude: 34.3853, longitude: 132.4553, timezone: "Asia/Tokyo", region: "asia" },
  // South Korea
  "seoul": { name: "Seoul", country: "South Korea", countryCode: "KR", latitude: 37.5665, longitude: 126.978, timezone: "Asia/Seoul", region: "asia" },
  "busan": { name: "Busan", country: "South Korea", countryCode: "KR", latitude: 35.1796, longitude: 129.0756, timezone: "Asia/Seoul", region: "asia" },
  "incheon": { name: "Incheon", country: "South Korea", countryCode: "KR", latitude: 37.4563, longitude: 126.7052, timezone: "Asia/Seoul", region: "asia" },
  "jeju": { name: "Jeju", country: "South Korea", countryCode: "KR", latitude: 33.4996, longitude: 126.5312, timezone: "Asia/Seoul", region: "asia" },
  // China
  "beijing": { name: "Beijing", country: "China", countryCode: "CN", latitude: 39.9042, longitude: 116.4074, timezone: "Asia/Shanghai", region: "asia" },
  "shanghai": { name: "Shanghai", country: "China", countryCode: "CN", latitude: 31.2304, longitude: 121.4737, timezone: "Asia/Shanghai", region: "asia" },
  "guangzhou": { name: "Guangzhou", country: "China", countryCode: "CN", latitude: 23.1291, longitude: 113.2644, timezone: "Asia/Shanghai", region: "asia" },
  "shenzhen": { name: "Shenzhen", country: "China", countryCode: "CN", latitude: 22.5431, longitude: 114.0579, timezone: "Asia/Shanghai", region: "asia" },
  "chengdu": { name: "Chengdu", country: "China", countryCode: "CN", latitude: 30.5728, longitude: 104.0668, timezone: "Asia/Shanghai", region: "asia" },
  "wuhan": { name: "Wuhan", country: "China", countryCode: "CN", latitude: 30.5928, longitude: 114.3055, timezone: "Asia/Shanghai", region: "asia" },
  "xian": { name: "Xi'an", country: "China", countryCode: "CN", latitude: 34.3416, longitude: 108.9398, timezone: "Asia/Shanghai", region: "asia" },
  "hangzhou": { name: "Hangzhou", country: "China", countryCode: "CN", latitude: 30.2741, longitude: 120.1551, timezone: "Asia/Shanghai", region: "asia" },
  "chongqing": { name: "Chongqing", country: "China", countryCode: "CN", latitude: 29.4316, longitude: 106.9123, timezone: "Asia/Shanghai", region: "asia" },
  "nanjing": { name: "Nanjing", country: "China", countryCode: "CN", latitude: 32.0603, longitude: 118.7969, timezone: "Asia/Shanghai", region: "asia" },
  "tianjin": { name: "Tianjin", country: "China", countryCode: "CN", latitude: 39.3434, longitude: 117.3616, timezone: "Asia/Shanghai", region: "asia" },
  "kunming": { name: "Kunming", country: "China", countryCode: "CN", latitude: 25.0389, longitude: 102.7183, timezone: "Asia/Shanghai", region: "asia" },
  "harbin": { name: "Harbin", country: "China", countryCode: "CN", latitude: 45.8038, longitude: 126.5350, timezone: "Asia/Shanghai", region: "asia" },
  // Hong Kong, Taiwan, Macau
  "hong-kong": { name: "Hong Kong", country: "Hong Kong", countryCode: "HK", latitude: 22.3193, longitude: 114.1694, timezone: "Asia/Hong_Kong", region: "asia" },
  "taipei": { name: "Taipei", country: "Taiwan", countryCode: "TW", latitude: 25.033, longitude: 121.5654, timezone: "Asia/Taipei", region: "asia" },
  "macau": { name: "Macau", country: "Macau", countryCode: "MO", latitude: 22.1987, longitude: 113.5439, timezone: "Asia/Macau", region: "asia" },
  // Southeast Asia
  "singapore": { name: "Singapore", country: "Singapore", countryCode: "SG", latitude: 1.3521, longitude: 103.8198, timezone: "Asia/Singapore", region: "asia" },
  "bangkok": { name: "Bangkok", country: "Thailand", countryCode: "TH", latitude: 13.7563, longitude: 100.5018, timezone: "Asia/Bangkok", region: "asia" },
  "chiang-mai": { name: "Chiang Mai", country: "Thailand", countryCode: "TH", latitude: 18.7883, longitude: 98.9853, timezone: "Asia/Bangkok", region: "asia" },
  "phuket": { name: "Phuket", country: "Thailand", countryCode: "TH", latitude: 7.8804, longitude: 98.3923, timezone: "Asia/Bangkok", region: "asia" },
  "pattaya": { name: "Pattaya", country: "Thailand", countryCode: "TH", latitude: 12.9236, longitude: 100.8825, timezone: "Asia/Bangkok", region: "asia" },
  "kuala-lumpur": { name: "Kuala Lumpur", country: "Malaysia", countryCode: "MY", latitude: 3.139, longitude: 101.6869, timezone: "Asia/Kuala_Lumpur", region: "asia" },
  "penang": { name: "Penang", country: "Malaysia", countryCode: "MY", latitude: 5.4164, longitude: 100.3327, timezone: "Asia/Kuala_Lumpur", region: "asia" },
  "johor-bahru": { name: "Johor Bahru", country: "Malaysia", countryCode: "MY", latitude: 1.4927, longitude: 103.7414, timezone: "Asia/Kuala_Lumpur", region: "asia" },
  "jakarta": { name: "Jakarta", country: "Indonesia", countryCode: "ID", latitude: -6.2088, longitude: 106.8456, timezone: "Asia/Jakarta", region: "asia" },
  "bali": { name: "Bali", country: "Indonesia", countryCode: "ID", latitude: -8.3405, longitude: 115.0920, timezone: "Asia/Makassar", region: "asia" },
  "surabaya": { name: "Surabaya", country: "Indonesia", countryCode: "ID", latitude: -7.2575, longitude: 112.7521, timezone: "Asia/Jakarta", region: "asia" },
  "bandung": { name: "Bandung", country: "Indonesia", countryCode: "ID", latitude: -6.9175, longitude: 107.6191, timezone: "Asia/Jakarta", region: "asia" },
  "yogyakarta": { name: "Yogyakarta", country: "Indonesia", countryCode: "ID", latitude: -7.7956, longitude: 110.3695, timezone: "Asia/Jakarta", region: "asia" },
  "medan": { name: "Medan", country: "Indonesia", countryCode: "ID", latitude: 3.5952, longitude: 98.6722, timezone: "Asia/Jakarta", region: "asia" },
  "manila": { name: "Manila", country: "Philippines", countryCode: "PH", latitude: 14.5995, longitude: 120.9842, timezone: "Asia/Manila", region: "asia" },
  "cebu": { name: "Cebu", country: "Philippines", countryCode: "PH", latitude: 10.3157, longitude: 123.8854, timezone: "Asia/Manila", region: "asia" },
  "davao": { name: "Davao", country: "Philippines", countryCode: "PH", latitude: 7.1907, longitude: 125.4553, timezone: "Asia/Manila", region: "asia" },
  "hanoi": { name: "Hanoi", country: "Vietnam", countryCode: "VN", latitude: 21.0278, longitude: 105.8342, timezone: "Asia/Ho_Chi_Minh", region: "asia" },
  "ho-chi-minh-city": { name: "Ho Chi Minh City", country: "Vietnam", countryCode: "VN", latitude: 10.8231, longitude: 106.6297, timezone: "Asia/Ho_Chi_Minh", region: "asia" },
  "da-nang": { name: "Da Nang", country: "Vietnam", countryCode: "VN", latitude: 16.0544, longitude: 108.2022, timezone: "Asia/Ho_Chi_Minh", region: "asia" },
  "phnom-penh": { name: "Phnom Penh", country: "Cambodia", countryCode: "KH", latitude: 11.5564, longitude: 104.9282, timezone: "Asia/Phnom_Penh", region: "asia" },
  "siem-reap": { name: "Siem Reap", country: "Cambodia", countryCode: "KH", latitude: 13.3633, longitude: 103.8600, timezone: "Asia/Phnom_Penh", region: "asia" },
  "yangon": { name: "Yangon", country: "Myanmar", countryCode: "MM", latitude: 16.8661, longitude: 96.1951, timezone: "Asia/Yangon", region: "asia" },
  "vientiane": { name: "Vientiane", country: "Laos", countryCode: "LA", latitude: 17.9757, longitude: 102.6331, timezone: "Asia/Vientiane", region: "asia" },
  "bandar-seri-begawan": { name: "Bandar Seri Begawan", country: "Brunei", countryCode: "BN", latitude: 4.9431, longitude: 114.9425, timezone: "Asia/Brunei", region: "asia" },
  // India
  "mumbai": { name: "Mumbai", country: "India", countryCode: "IN", latitude: 19.076, longitude: 72.8777, timezone: "Asia/Kolkata", region: "asia" },
  "delhi": { name: "Delhi", country: "India", countryCode: "IN", latitude: 28.7041, longitude: 77.1025, timezone: "Asia/Kolkata", region: "asia" },
  "bangalore": { name: "Bangalore", country: "India", countryCode: "IN", latitude: 12.9716, longitude: 77.5946, timezone: "Asia/Kolkata", region: "asia" },
  "chennai": { name: "Chennai", country: "India", countryCode: "IN", latitude: 13.0827, longitude: 80.2707, timezone: "Asia/Kolkata", region: "asia" },
  "kolkata": { name: "Kolkata", country: "India", countryCode: "IN", latitude: 22.5726, longitude: 88.3639, timezone: "Asia/Kolkata", region: "asia" },
  "hyderabad": { name: "Hyderabad", country: "India", countryCode: "IN", latitude: 17.385, longitude: 78.4867, timezone: "Asia/Kolkata", region: "asia" },
  "pune": { name: "Pune", country: "India", countryCode: "IN", latitude: 18.5204, longitude: 73.8567, timezone: "Asia/Kolkata", region: "asia" },
  "ahmedabad": { name: "Ahmedabad", country: "India", countryCode: "IN", latitude: 23.0225, longitude: 72.5714, timezone: "Asia/Kolkata", region: "asia" },
  "jaipur": { name: "Jaipur", country: "India", countryCode: "IN", latitude: 26.9124, longitude: 75.7873, timezone: "Asia/Kolkata", region: "asia" },
  "chandigarh": { name: "Chandigarh", country: "India", countryCode: "IN", latitude: 30.7333, longitude: 76.7794, timezone: "Asia/Kolkata", region: "asia" },
  "lucknow": { name: "Lucknow", country: "India", countryCode: "IN", latitude: 26.8467, longitude: 80.9462, timezone: "Asia/Kolkata", region: "asia" },
  "kanpur": { name: "Kanpur", country: "India", countryCode: "IN", latitude: 26.4499, longitude: 80.3319, timezone: "Asia/Kolkata", region: "asia" },
  "nagpur": { name: "Nagpur", country: "India", countryCode: "IN", latitude: 21.1458, longitude: 79.0882, timezone: "Asia/Kolkata", region: "asia" },
  "indore": { name: "Indore", country: "India", countryCode: "IN", latitude: 22.7196, longitude: 75.8577, timezone: "Asia/Kolkata", region: "asia" },
  "bhopal": { name: "Bhopal", country: "India", countryCode: "IN", latitude: 23.2599, longitude: 77.4126, timezone: "Asia/Kolkata", region: "asia" },
  "visakhapatnam": { name: "Visakhapatnam", country: "India", countryCode: "IN", latitude: 17.6868, longitude: 83.2185, timezone: "Asia/Kolkata", region: "asia" },
  "patna": { name: "Patna", country: "India", countryCode: "IN", latitude: 25.6093, longitude: 85.1376, timezone: "Asia/Kolkata", region: "asia" },
  "surat": { name: "Surat", country: "India", countryCode: "IN", latitude: 21.1702, longitude: 72.8311, timezone: "Asia/Kolkata", region: "asia" },
  "kochi": { name: "Kochi", country: "India", countryCode: "IN", latitude: 9.9312, longitude: 76.2673, timezone: "Asia/Kolkata", region: "asia" },
  "goa": { name: "Goa", country: "India", countryCode: "IN", latitude: 15.2993, longitude: 74.1240, timezone: "Asia/Kolkata", region: "asia" },
  "varanasi": { name: "Varanasi", country: "India", countryCode: "IN", latitude: 25.3176, longitude: 82.9739, timezone: "Asia/Kolkata", region: "asia" },
  "coimbatore": { name: "Coimbatore", country: "India", countryCode: "IN", latitude: 11.0168, longitude: 76.9558, timezone: "Asia/Kolkata", region: "asia" },
  "thiruvananthapuram": { name: "Thiruvananthapuram", country: "India", countryCode: "IN", latitude: 8.5241, longitude: 76.9366, timezone: "Asia/Kolkata", region: "asia" },
  // Pakistan
  "karachi": { name: "Karachi", country: "Pakistan", countryCode: "PK", latitude: 24.8607, longitude: 67.0011, timezone: "Asia/Karachi", region: "asia" },
  "lahore": { name: "Lahore", country: "Pakistan", countryCode: "PK", latitude: 31.5204, longitude: 74.3587, timezone: "Asia/Karachi", region: "asia" },
  "islamabad": { name: "Islamabad", country: "Pakistan", countryCode: "PK", latitude: 33.6844, longitude: 73.0479, timezone: "Asia/Karachi", region: "asia" },
  "faisalabad": { name: "Faisalabad", country: "Pakistan", countryCode: "PK", latitude: 31.4504, longitude: 73.1350, timezone: "Asia/Karachi", region: "asia" },
  "rawalpindi": { name: "Rawalpindi", country: "Pakistan", countryCode: "PK", latitude: 33.5651, longitude: 73.0169, timezone: "Asia/Karachi", region: "asia" },
  "peshawar": { name: "Peshawar", country: "Pakistan", countryCode: "PK", latitude: 34.0151, longitude: 71.5249, timezone: "Asia/Karachi", region: "asia" },
  // Bangladesh, Sri Lanka, Nepal
  "dhaka": { name: "Dhaka", country: "Bangladesh", countryCode: "BD", latitude: 23.8103, longitude: 90.4125, timezone: "Asia/Dhaka", region: "asia" },
  "chittagong": { name: "Chittagong", country: "Bangladesh", countryCode: "BD", latitude: 22.3569, longitude: 91.7832, timezone: "Asia/Dhaka", region: "asia" },
  "colombo": { name: "Colombo", country: "Sri Lanka", countryCode: "LK", latitude: 6.9271, longitude: 79.8612, timezone: "Asia/Colombo", region: "asia" },
  "kathmandu": { name: "Kathmandu", country: "Nepal", countryCode: "NP", latitude: 27.7172, longitude: 85.324, timezone: "Asia/Kathmandu", region: "asia" },
  // Middle East
  "dubai": { name: "Dubai", country: "United Arab Emirates", countryCode: "AE", latitude: 25.2048, longitude: 55.2708, timezone: "Asia/Dubai", region: "asia" },
  "abu-dhabi": { name: "Abu Dhabi", country: "United Arab Emirates", countryCode: "AE", latitude: 24.4539, longitude: 54.3773, timezone: "Asia/Dubai", region: "asia" },
  "sharjah": { name: "Sharjah", country: "United Arab Emirates", countryCode: "AE", latitude: 25.3463, longitude: 55.4209, timezone: "Asia/Dubai", region: "asia" },
  "doha": { name: "Doha", country: "Qatar", countryCode: "QA", latitude: 25.2854, longitude: 51.531, timezone: "Asia/Qatar", region: "asia" },
  "riyadh": { name: "Riyadh", country: "Saudi Arabia", countryCode: "SA", latitude: 24.7136, longitude: 46.6753, timezone: "Asia/Riyadh", region: "asia" },
  "jeddah": { name: "Jeddah", country: "Saudi Arabia", countryCode: "SA", latitude: 21.4858, longitude: 39.1925, timezone: "Asia/Riyadh", region: "asia" },
  "mecca": { name: "Mecca", country: "Saudi Arabia", countryCode: "SA", latitude: 21.3891, longitude: 39.8579, timezone: "Asia/Riyadh", region: "asia" },
  "medina": { name: "Medina", country: "Saudi Arabia", countryCode: "SA", latitude: 24.5247, longitude: 39.5692, timezone: "Asia/Riyadh", region: "asia" },
  "dammam": { name: "Dammam", country: "Saudi Arabia", countryCode: "SA", latitude: 26.4207, longitude: 50.0888, timezone: "Asia/Riyadh", region: "asia" },
  "kuwait-city": { name: "Kuwait City", country: "Kuwait", countryCode: "KW", latitude: 29.3759, longitude: 47.9774, timezone: "Asia/Kuwait", region: "asia" },
  "muscat": { name: "Muscat", country: "Oman", countryCode: "OM", latitude: 23.5880, longitude: 58.3829, timezone: "Asia/Muscat", region: "asia" },
  "manama": { name: "Manama", country: "Bahrain", countryCode: "BH", latitude: 26.2285, longitude: 50.5860, timezone: "Asia/Bahrain", region: "asia" },
  "amman": { name: "Amman", country: "Jordan", countryCode: "JO", latitude: 31.9454, longitude: 35.9284, timezone: "Asia/Amman", region: "asia" },
  "beirut": { name: "Beirut", country: "Lebanon", countryCode: "LB", latitude: 33.8938, longitude: 35.5018, timezone: "Asia/Beirut", region: "asia" },
  "baghdad": { name: "Baghdad", country: "Iraq", countryCode: "IQ", latitude: 33.3152, longitude: 44.3661, timezone: "Asia/Baghdad", region: "asia" },
  "tehran": { name: "Tehran", country: "Iran", countryCode: "IR", latitude: 35.6892, longitude: 51.3890, timezone: "Asia/Tehran", region: "asia" },
  "tel-aviv": { name: "Tel Aviv", country: "Israel", countryCode: "IL", latitude: 32.0853, longitude: 34.7818, timezone: "Asia/Jerusalem", region: "asia" },
  "jerusalem": { name: "Jerusalem", country: "Israel", countryCode: "IL", latitude: 31.7683, longitude: 35.2137, timezone: "Asia/Jerusalem", region: "asia" },
  // Central Asia
  "tashkent": { name: "Tashkent", country: "Uzbekistan", countryCode: "UZ", latitude: 41.2995, longitude: 69.2401, timezone: "Asia/Tashkent", region: "asia" },
  "almaty": { name: "Almaty", country: "Kazakhstan", countryCode: "KZ", latitude: 43.2220, longitude: 76.8512, timezone: "Asia/Almaty", region: "asia" },
  "astana": { name: "Astana", country: "Kazakhstan", countryCode: "KZ", latitude: 51.1694, longitude: 71.4491, timezone: "Asia/Almaty", region: "asia" },
  "tbilisi": { name: "Tbilisi", country: "Georgia", countryCode: "GE", latitude: 41.7151, longitude: 44.8271, timezone: "Asia/Tbilisi", region: "asia" },
  "baku": { name: "Baku", country: "Azerbaijan", countryCode: "AZ", latitude: 40.4093, longitude: 49.8671, timezone: "Asia/Baku", region: "asia" },
  "yerevan": { name: "Yerevan", country: "Armenia", countryCode: "AM", latitude: 40.1792, longitude: 44.4991, timezone: "Asia/Yerevan", region: "asia" },
  "bishkek": { name: "Bishkek", country: "Kyrgyzstan", countryCode: "KG", latitude: 42.8746, longitude: 74.5698, timezone: "Asia/Bishkek", region: "asia" },
  "dushanbe": { name: "Dushanbe", country: "Tajikistan", countryCode: "TJ", latitude: 38.5598, longitude: 68.7740, timezone: "Asia/Dushanbe", region: "asia" },
  // Mongolia
  "ulaanbaatar": { name: "Ulaanbaatar", country: "Mongolia", countryCode: "MN", latitude: 47.8864, longitude: 106.9057, timezone: "Asia/Ulaanbaatar", region: "asia" },
  // Additional Asia
  "nha-trang": { name: "Nha Trang", country: "Vietnam", countryCode: "VN", latitude: 12.2388, longitude: 109.1967, timezone: "Asia/Ho_Chi_Minh", region: "asia" },
  "makassar": { name: "Makassar", country: "Indonesia", countryCode: "ID", latitude: -5.1477, longitude: 119.4327, timezone: "Asia/Makassar", region: "asia" },
  "semarang": { name: "Semarang", country: "Indonesia", countryCode: "ID", latitude: -6.9666, longitude: 110.4196, timezone: "Asia/Jakarta", region: "asia" },
  "palembang": { name: "Palembang", country: "Indonesia", countryCode: "ID", latitude: -2.9761, longitude: 104.7754, timezone: "Asia/Jakarta", region: "asia" },
  "kota-kinabalu": { name: "Kota Kinabalu", country: "Malaysia", countryCode: "MY", latitude: 5.9804, longitude: 116.0735, timezone: "Asia/Kuching", region: "asia" },
  "quezon-city": { name: "Quezon City", country: "Philippines", countryCode: "PH", latitude: 14.6760, longitude: 121.0437, timezone: "Asia/Manila", region: "asia" },
  "nagasaki": { name: "Nagasaki", country: "Japan", countryCode: "JP", latitude: 32.7503, longitude: 129.8779, timezone: "Asia/Tokyo", region: "asia" },
  "okinawa": { name: "Okinawa", country: "Japan", countryCode: "JP", latitude: 26.3344, longitude: 127.8056, timezone: "Asia/Tokyo", region: "asia" },
  "daegu": { name: "Daegu", country: "South Korea", countryCode: "KR", latitude: 35.8714, longitude: 128.6014, timezone: "Asia/Seoul", region: "asia" },
  "dalian": { name: "Dalian", country: "China", countryCode: "CN", latitude: 38.9140, longitude: 121.6147, timezone: "Asia/Shanghai", region: "asia" },
  "qingdao": { name: "Qingdao", country: "China", countryCode: "CN", latitude: 36.0671, longitude: 120.3826, timezone: "Asia/Shanghai", region: "asia" },
  "xiamen": { name: "Xiamen", country: "China", countryCode: "CN", latitude: 24.4798, longitude: 118.0894, timezone: "Asia/Shanghai", region: "asia" },
  "lhasa": { name: "Lhasa", country: "China", countryCode: "CN", latitude: 29.6500, longitude: 91.1000, timezone: "Asia/Shanghai", region: "asia" },
  "multan": { name: "Multan", country: "Pakistan", countryCode: "PK", latitude: 30.1575, longitude: 71.5249, timezone: "Asia/Karachi", region: "asia" },
  "damascus": { name: "Damascus", country: "Syria", countryCode: "SY", latitude: 33.5138, longitude: 36.2765, timezone: "Asia/Damascus", region: "asia" },
  "sanaa": { name: "Sanaa", country: "Yemen", countryCode: "YE", latitude: 15.3694, longitude: 44.1910, timezone: "Asia/Aden", region: "asia" },
  "kabul": { name: "Kabul", country: "Afghanistan", countryCode: "AF", latitude: 34.5553, longitude: 69.2075, timezone: "Asia/Kabul", region: "asia" },
  "ashgabat": { name: "Ashgabat", country: "Turkmenistan", countryCode: "TM", latitude: 37.9601, longitude: 58.3261, timezone: "Asia/Ashgabat", region: "asia" },
  "samarkand": { name: "Samarkand", country: "Uzbekistan", countryCode: "UZ", latitude: 39.6550, longitude: 66.9597, timezone: "Asia/Samarkand", region: "asia" },
  "male": { name: "Malé", country: "Maldives", countryCode: "MV", latitude: 4.1755, longitude: 73.5093, timezone: "Indian/Maldives", region: "asia" },
  "thimphu": { name: "Thimphu", country: "Bhutan", countryCode: "BT", latitude: 27.4728, longitude: 89.6390, timezone: "Asia/Thimphu", region: "asia" },
  "erbil": { name: "Erbil", country: "Iraq", countryCode: "IQ", latitude: 36.1912, longitude: 44.0094, timezone: "Asia/Baghdad", region: "asia" },
  "batumi": { name: "Batumi", country: "Georgia", countryCode: "GE", latitude: 41.6168, longitude: 41.6367, timezone: "Asia/Tbilisi", region: "asia" },
  "isfahan": { name: "Isfahan", country: "Iran", countryCode: "IR", latitude: 32.6546, longitude: 51.6680, timezone: "Asia/Tehran", region: "asia" },
  "suzhou": { name: "Suzhou", country: "China", countryCode: "CN", latitude: 31.2990, longitude: 120.5853, timezone: "Asia/Shanghai", region: "asia" },
  "guilin": { name: "Guilin", country: "China", countryCode: "CN", latitude: 25.2736, longitude: 110.2907, timezone: "Asia/Shanghai", region: "asia" },
  "haikou": { name: "Haikou", country: "China", countryCode: "CN", latitude: 20.0174, longitude: 110.3492, timezone: "Asia/Shanghai", region: "asia" },
  "langkawi": { name: "Langkawi", country: "Malaysia", countryCode: "MY", latitude: 6.3500, longitude: 99.8000, timezone: "Asia/Kuala_Lumpur", region: "asia" },
  "krabi": { name: "Krabi", country: "Thailand", countryCode: "TH", latitude: 8.0863, longitude: 98.9063, timezone: "Asia/Bangkok", region: "asia" },

  // ═══════════════════════════════════════════════════════════════════
  // LATIN AMERICA (~60)
  // ═══════════════════════════════════════════════════════════════════

  // Mexico
  "mexico-city": { name: "Mexico City", country: "Mexico", countryCode: "MX", latitude: 19.4326, longitude: -99.1332, timezone: "America/Mexico_City", region: "latin-america" },
  "cancun": { name: "Cancún", country: "Mexico", countryCode: "MX", latitude: 21.1619, longitude: -86.8515, timezone: "America/Cancun", region: "latin-america" },
  "guadalajara": { name: "Guadalajara", country: "Mexico", countryCode: "MX", latitude: 20.6597, longitude: -103.3496, timezone: "America/Mexico_City", region: "latin-america" },
  "monterrey": { name: "Monterrey", country: "Mexico", countryCode: "MX", latitude: 25.6866, longitude: -100.3161, timezone: "America/Monterrey", region: "latin-america" },
  "puebla": { name: "Puebla", country: "Mexico", countryCode: "MX", latitude: 19.0414, longitude: -98.2063, timezone: "America/Mexico_City", region: "latin-america" },
  "tijuana": { name: "Tijuana", country: "Mexico", countryCode: "MX", latitude: 32.5149, longitude: -117.0382, timezone: "America/Tijuana", region: "latin-america" },
  "playa-del-carmen": { name: "Playa del Carmen", country: "Mexico", countryCode: "MX", latitude: 20.6296, longitude: -87.0739, timezone: "America/Cancun", region: "latin-america" },
  "merida": { name: "Mérida", country: "Mexico", countryCode: "MX", latitude: 20.9674, longitude: -89.5926, timezone: "America/Merida", region: "latin-america" },
  // Brazil
  "sao-paulo": { name: "São Paulo", country: "Brazil", countryCode: "BR", latitude: -23.5505, longitude: -46.6333, timezone: "America/Sao_Paulo", region: "latin-america" },
  "rio-de-janeiro": { name: "Rio de Janeiro", country: "Brazil", countryCode: "BR", latitude: -22.9068, longitude: -43.1729, timezone: "America/Sao_Paulo", region: "latin-america" },
  "brasilia": { name: "Brasília", country: "Brazil", countryCode: "BR", latitude: -15.7975, longitude: -47.8919, timezone: "America/Sao_Paulo", region: "latin-america" },
  "salvador": { name: "Salvador", country: "Brazil", countryCode: "BR", latitude: -12.9714, longitude: -38.5124, timezone: "America/Bahia", region: "latin-america" },
  "fortaleza": { name: "Fortaleza", country: "Brazil", countryCode: "BR", latitude: -3.7172, longitude: -38.5433, timezone: "America/Fortaleza", region: "latin-america" },
  "belo-horizonte": { name: "Belo Horizonte", country: "Brazil", countryCode: "BR", latitude: -19.9191, longitude: -43.9386, timezone: "America/Sao_Paulo", region: "latin-america" },
  "manaus": { name: "Manaus", country: "Brazil", countryCode: "BR", latitude: -3.1190, longitude: -60.0217, timezone: "America/Manaus", region: "latin-america" },
  "curitiba": { name: "Curitiba", country: "Brazil", countryCode: "BR", latitude: -25.4284, longitude: -49.2733, timezone: "America/Sao_Paulo", region: "latin-america" },
  "recife": { name: "Recife", country: "Brazil", countryCode: "BR", latitude: -8.0476, longitude: -34.8770, timezone: "America/Recife", region: "latin-america" },
  "porto-alegre": { name: "Porto Alegre", country: "Brazil", countryCode: "BR", latitude: -30.0346, longitude: -51.2177, timezone: "America/Sao_Paulo", region: "latin-america" },
  "florianopolis": { name: "Florianópolis", country: "Brazil", countryCode: "BR", latitude: -27.5954, longitude: -48.5480, timezone: "America/Sao_Paulo", region: "latin-america" },
  // Argentina
  "buenos-aires": { name: "Buenos Aires", country: "Argentina", countryCode: "AR", latitude: -34.6037, longitude: -58.3816, timezone: "America/Argentina/Buenos_Aires", region: "latin-america" },
  "cordoba": { name: "Córdoba", country: "Argentina", countryCode: "AR", latitude: -31.4201, longitude: -64.1888, timezone: "America/Argentina/Cordoba", region: "latin-america" },
  "mendoza": { name: "Mendoza", country: "Argentina", countryCode: "AR", latitude: -32.8895, longitude: -68.8458, timezone: "America/Argentina/Mendoza", region: "latin-america" },
  "bariloche": { name: "Bariloche", country: "Argentina", countryCode: "AR", latitude: -41.1335, longitude: -71.3103, timezone: "America/Argentina/Buenos_Aires", region: "latin-america" },
  // Colombia
  "bogota": { name: "Bogotá", country: "Colombia", countryCode: "CO", latitude: 4.711, longitude: -74.0721, timezone: "America/Bogota", region: "latin-america" },
  "medellin": { name: "Medellín", country: "Colombia", countryCode: "CO", latitude: 6.2476, longitude: -75.5658, timezone: "America/Bogota", region: "latin-america" },
  "cartagena": { name: "Cartagena", country: "Colombia", countryCode: "CO", latitude: 10.3910, longitude: -75.5364, timezone: "America/Bogota", region: "latin-america" },
  "cali": { name: "Cali", country: "Colombia", countryCode: "CO", latitude: 3.4516, longitude: -76.5320, timezone: "America/Bogota", region: "latin-america" },
  // Peru
  "lima": { name: "Lima", country: "Peru", countryCode: "PE", latitude: -12.0464, longitude: -77.0428, timezone: "America/Lima", region: "latin-america" },
  "cusco": { name: "Cusco", country: "Peru", countryCode: "PE", latitude: -13.5319, longitude: -71.9675, timezone: "America/Lima", region: "latin-america" },
  // Chile
  "santiago": { name: "Santiago", country: "Chile", countryCode: "CL", latitude: -33.4489, longitude: -70.6693, timezone: "America/Santiago", region: "latin-america" },
  "valparaiso": { name: "Valparaíso", country: "Chile", countryCode: "CL", latitude: -33.0472, longitude: -71.6127, timezone: "America/Santiago", region: "latin-america" },
  // Ecuador
  "quito": { name: "Quito", country: "Ecuador", countryCode: "EC", latitude: -0.1807, longitude: -78.4678, timezone: "America/Guayaquil", region: "latin-america" },
  "guayaquil": { name: "Guayaquil", country: "Ecuador", countryCode: "EC", latitude: -2.1894, longitude: -79.8891, timezone: "America/Guayaquil", region: "latin-america" },
  // Other South America
  "montevideo": { name: "Montevideo", country: "Uruguay", countryCode: "UY", latitude: -34.9011, longitude: -56.1645, timezone: "America/Montevideo", region: "latin-america" },
  "asuncion": { name: "Asunción", country: "Paraguay", countryCode: "PY", latitude: -25.2637, longitude: -57.5759, timezone: "America/Asuncion", region: "latin-america" },
  "la-paz": { name: "La Paz", country: "Bolivia", countryCode: "BO", latitude: -16.4897, longitude: -68.1193, timezone: "America/La_Paz", region: "latin-america" },
  "caracas": { name: "Caracas", country: "Venezuela", countryCode: "VE", latitude: 10.4806, longitude: -66.9036, timezone: "America/Caracas", region: "latin-america" },
  "georgetown": { name: "Georgetown", country: "Guyana", countryCode: "GY", latitude: 6.8013, longitude: -58.1551, timezone: "America/Guyana", region: "latin-america" },
  "paramaribo": { name: "Paramaribo", country: "Suriname", countryCode: "SR", latitude: 5.8520, longitude: -55.2038, timezone: "America/Paramaribo", region: "latin-america" },
  // Central America & Caribbean
  "havana": { name: "Havana", country: "Cuba", countryCode: "CU", latitude: 23.1136, longitude: -82.3666, timezone: "America/Havana", region: "latin-america" },
  "panama-city": { name: "Panama City", country: "Panama", countryCode: "PA", latitude: 8.9824, longitude: -79.5199, timezone: "America/Panama", region: "latin-america" },
  "san-juan": { name: "San Juan", country: "Puerto Rico", countryCode: "PR", latitude: 18.4655, longitude: -66.1057, timezone: "America/Puerto_Rico", region: "latin-america" },
  "san-jose-cr": { name: "San José", country: "Costa Rica", countryCode: "CR", latitude: 9.9281, longitude: -84.0907, timezone: "America/Costa_Rica", region: "latin-america" },
  "guatemala-city": { name: "Guatemala City", country: "Guatemala", countryCode: "GT", latitude: 14.6349, longitude: -90.5069, timezone: "America/Guatemala", region: "latin-america" },
  "tegucigalpa": { name: "Tegucigalpa", country: "Honduras", countryCode: "HN", latitude: 14.0723, longitude: -87.1921, timezone: "America/Tegucigalpa", region: "latin-america" },
  "san-salvador": { name: "San Salvador", country: "El Salvador", countryCode: "SV", latitude: 13.6929, longitude: -89.2182, timezone: "America/El_Salvador", region: "latin-america" },
  "managua": { name: "Managua", country: "Nicaragua", countryCode: "NI", latitude: 12.1150, longitude: -86.2362, timezone: "America/Managua", region: "latin-america" },
  "kingston": { name: "Kingston", country: "Jamaica", countryCode: "JM", latitude: 18.0179, longitude: -76.8099, timezone: "America/Jamaica", region: "latin-america" },
  "santo-domingo": { name: "Santo Domingo", country: "Dominican Republic", countryCode: "DO", latitude: 18.4861, longitude: -69.9312, timezone: "America/Santo_Domingo", region: "latin-america" },
  "port-au-prince": { name: "Port-au-Prince", country: "Haiti", countryCode: "HT", latitude: 18.5944, longitude: -72.3074, timezone: "America/Port-au-Prince", region: "latin-america" },
  "nassau": { name: "Nassau", country: "Bahamas", countryCode: "BS", latitude: 25.0343, longitude: -77.3963, timezone: "America/Nassau", region: "latin-america" },
  "port-of-spain": { name: "Port of Spain", country: "Trinidad and Tobago", countryCode: "TT", latitude: 10.6596, longitude: -61.5086, timezone: "America/Port_of_Spain", region: "latin-america" },
  "punta-cana": { name: "Punta Cana", country: "Dominican Republic", countryCode: "DO", latitude: 18.5601, longitude: -68.3725, timezone: "America/Santo_Domingo", region: "latin-america" },
  "belize-city": { name: "Belize City", country: "Belize", countryCode: "BZ", latitude: 17.4987, longitude: -88.1886, timezone: "America/Belize", region: "latin-america" },
  "bridgetown": { name: "Bridgetown", country: "Barbados", countryCode: "BB", latitude: 13.0969, longitude: -59.6145, timezone: "America/Barbados", region: "latin-america" },
  "aruba": { name: "Oranjestad", country: "Aruba", countryCode: "AW", latitude: 12.5093, longitude: -70.0086, timezone: "America/Aruba", region: "latin-america" },
  "curacao": { name: "Willemstad", country: "Curaçao", countryCode: "CW", latitude: 12.1696, longitude: -68.9900, timezone: "America/Curacao", region: "latin-america" },
  "santa-cruz": { name: "Santa Cruz", country: "Bolivia", countryCode: "BO", latitude: -17.7833, longitude: -63.1821, timezone: "America/La_Paz", region: "latin-america" },
  "leon": { name: "León", country: "Mexico", countryCode: "MX", latitude: 21.1221, longitude: -101.6820, timezone: "America/Mexico_City", region: "latin-america" },
  "cabo-san-lucas": { name: "Cabo San Lucas", country: "Mexico", countryCode: "MX", latitude: 22.8905, longitude: -109.9167, timezone: "America/Mazatlan", region: "latin-america" },
  "puerto-vallarta": { name: "Puerto Vallarta", country: "Mexico", countryCode: "MX", latitude: 20.6534, longitude: -105.2253, timezone: "America/Mexico_City", region: "latin-america" },
  "sucre": { name: "Sucre", country: "Bolivia", countryCode: "BO", latitude: -19.0196, longitude: -65.2619, timezone: "America/La_Paz", region: "latin-america" },
  "barranquilla": { name: "Barranquilla", country: "Colombia", countryCode: "CO", latitude: 10.9685, longitude: -74.7813, timezone: "America/Bogota", region: "latin-america" },

  // ═══════════════════════════════════════════════════════════════════
  // AFRICA (~50)
  // ═══════════════════════════════════════════════════════════════════

  // North Africa
  "cairo": { name: "Cairo", country: "Egypt", countryCode: "EG", latitude: 30.0444, longitude: 31.2357, timezone: "Africa/Cairo", region: "africa" },
  "alexandria": { name: "Alexandria", country: "Egypt", countryCode: "EG", latitude: 31.2001, longitude: 29.9187, timezone: "Africa/Cairo", region: "africa" },
  "luxor": { name: "Luxor", country: "Egypt", countryCode: "EG", latitude: 25.6872, longitude: 32.6396, timezone: "Africa/Cairo", region: "africa" },
  "casablanca": { name: "Casablanca", country: "Morocco", countryCode: "MA", latitude: 33.5731, longitude: -7.5898, timezone: "Africa/Casablanca", region: "africa" },
  "marrakech": { name: "Marrakech", country: "Morocco", countryCode: "MA", latitude: 31.6295, longitude: -7.9811, timezone: "Africa/Casablanca", region: "africa" },
  "rabat": { name: "Rabat", country: "Morocco", countryCode: "MA", latitude: 34.0209, longitude: -6.8416, timezone: "Africa/Casablanca", region: "africa" },
  "fez": { name: "Fez", country: "Morocco", countryCode: "MA", latitude: 34.0181, longitude: -5.0078, timezone: "Africa/Casablanca", region: "africa" },
  "tangier": { name: "Tangier", country: "Morocco", countryCode: "MA", latitude: 35.7595, longitude: -5.8340, timezone: "Africa/Casablanca", region: "africa" },
  "tunis": { name: "Tunis", country: "Tunisia", countryCode: "TN", latitude: 36.8065, longitude: 10.1815, timezone: "Africa/Tunis", region: "africa" },
  "algiers": { name: "Algiers", country: "Algeria", countryCode: "DZ", latitude: 36.7538, longitude: 3.0588, timezone: "Africa/Algiers", region: "africa" },
  "tripoli": { name: "Tripoli", country: "Libya", countryCode: "LY", latitude: 32.8872, longitude: 13.1913, timezone: "Africa/Tripoli", region: "africa" },
  // West Africa
  "lagos": { name: "Lagos", country: "Nigeria", countryCode: "NG", latitude: 6.5244, longitude: 3.3792, timezone: "Africa/Lagos", region: "africa" },
  "abuja": { name: "Abuja", country: "Nigeria", countryCode: "NG", latitude: 9.0765, longitude: 7.3986, timezone: "Africa/Lagos", region: "africa" },
  "kano": { name: "Kano", country: "Nigeria", countryCode: "NG", latitude: 12.0022, longitude: 8.5920, timezone: "Africa/Lagos", region: "africa" },
  "port-harcourt": { name: "Port Harcourt", country: "Nigeria", countryCode: "NG", latitude: 4.8156, longitude: 7.0498, timezone: "Africa/Lagos", region: "africa" },
  "ibadan": { name: "Ibadan", country: "Nigeria", countryCode: "NG", latitude: 7.3775, longitude: 3.9470, timezone: "Africa/Lagos", region: "africa" },
  "accra": { name: "Accra", country: "Ghana", countryCode: "GH", latitude: 5.6037, longitude: -0.187, timezone: "Africa/Accra", region: "africa" },
  "dakar": { name: "Dakar", country: "Senegal", countryCode: "SN", latitude: 14.7167, longitude: -17.4677, timezone: "Africa/Dakar", region: "africa" },
  "abidjan": { name: "Abidjan", country: "Ivory Coast", countryCode: "CI", latitude: 5.3600, longitude: -4.0083, timezone: "Africa/Abidjan", region: "africa" },
  "bamako": { name: "Bamako", country: "Mali", countryCode: "ML", latitude: 12.6392, longitude: -8.0029, timezone: "Africa/Bamako", region: "africa" },
  "ouagadougou": { name: "Ouagadougou", country: "Burkina Faso", countryCode: "BF", latitude: 12.3714, longitude: -1.5197, timezone: "Africa/Ouagadougou", region: "africa" },
  "conakry": { name: "Conakry", country: "Guinea", countryCode: "GN", latitude: 9.6412, longitude: -13.5784, timezone: "Africa/Conakry", region: "africa" },
  "lome": { name: "Lomé", country: "Togo", countryCode: "TG", latitude: 6.1256, longitude: 1.2254, timezone: "Africa/Lome", region: "africa" },
  "cotonou": { name: "Cotonou", country: "Benin", countryCode: "BJ", latitude: 6.3654, longitude: 2.4183, timezone: "Africa/Porto-Novo", region: "africa" },
  // East Africa
  "nairobi": { name: "Nairobi", country: "Kenya", countryCode: "KE", latitude: -1.2921, longitude: 36.8219, timezone: "Africa/Nairobi", region: "africa" },
  "mombasa": { name: "Mombasa", country: "Kenya", countryCode: "KE", latitude: -4.0435, longitude: 39.6682, timezone: "Africa/Nairobi", region: "africa" },
  "addis-ababa": { name: "Addis Ababa", country: "Ethiopia", countryCode: "ET", latitude: 9.0246, longitude: 38.7468, timezone: "Africa/Addis_Ababa", region: "africa" },
  "dar-es-salaam": { name: "Dar es Salaam", country: "Tanzania", countryCode: "TZ", latitude: -6.7924, longitude: 39.2083, timezone: "Africa/Dar_es_Salaam", region: "africa" },
  "zanzibar": { name: "Zanzibar", country: "Tanzania", countryCode: "TZ", latitude: -6.1659, longitude: 39.2026, timezone: "Africa/Dar_es_Salaam", region: "africa" },
  "kampala": { name: "Kampala", country: "Uganda", countryCode: "UG", latitude: 0.3476, longitude: 32.5825, timezone: "Africa/Kampala", region: "africa" },
  "kigali": { name: "Kigali", country: "Rwanda", countryCode: "RW", latitude: -1.9403, longitude: 29.8739, timezone: "Africa/Kigali", region: "africa" },
  "mogadishu": { name: "Mogadishu", country: "Somalia", countryCode: "SO", latitude: 2.0469, longitude: 45.3182, timezone: "Africa/Mogadishu", region: "africa" },
  "djibouti": { name: "Djibouti", country: "Djibouti", countryCode: "DJ", latitude: 11.5721, longitude: 43.1456, timezone: "Africa/Djibouti", region: "africa" },
  // Southern Africa
  "johannesburg": { name: "Johannesburg", country: "South Africa", countryCode: "ZA", latitude: -26.2041, longitude: 28.0473, timezone: "Africa/Johannesburg", region: "africa" },
  "cape-town": { name: "Cape Town", country: "South Africa", countryCode: "ZA", latitude: -33.9249, longitude: 18.4241, timezone: "Africa/Johannesburg", region: "africa" },
  "durban": { name: "Durban", country: "South Africa", countryCode: "ZA", latitude: -29.8587, longitude: 31.0218, timezone: "Africa/Johannesburg", region: "africa" },
  "pretoria": { name: "Pretoria", country: "South Africa", countryCode: "ZA", latitude: -25.7479, longitude: 28.2293, timezone: "Africa/Johannesburg", region: "africa" },
  "lusaka": { name: "Lusaka", country: "Zambia", countryCode: "ZM", latitude: -15.3875, longitude: 28.3228, timezone: "Africa/Lusaka", region: "africa" },
  "harare": { name: "Harare", country: "Zimbabwe", countryCode: "ZW", latitude: -17.8292, longitude: 31.0522, timezone: "Africa/Harare", region: "africa" },
  "maputo": { name: "Maputo", country: "Mozambique", countryCode: "MZ", latitude: -25.9692, longitude: 32.5732, timezone: "Africa/Maputo", region: "africa" },
  "windhoek": { name: "Windhoek", country: "Namibia", countryCode: "NA", latitude: -22.5609, longitude: 17.0658, timezone: "Africa/Windhoek", region: "africa" },
  "gaborone": { name: "Gaborone", country: "Botswana", countryCode: "BW", latitude: -24.6282, longitude: 25.9231, timezone: "Africa/Gaborone", region: "africa" },
  // Central Africa
  "kinshasa": { name: "Kinshasa", country: "Democratic Republic of the Congo", countryCode: "CD", latitude: -4.4419, longitude: 15.2663, timezone: "Africa/Kinshasa", region: "africa" },
  "luanda": { name: "Luanda", country: "Angola", countryCode: "AO", latitude: -8.8390, longitude: 13.2894, timezone: "Africa/Luanda", region: "africa" },
  "douala": { name: "Douala", country: "Cameroon", countryCode: "CM", latitude: 4.0511, longitude: 9.7679, timezone: "Africa/Douala", region: "africa" },
  "libreville": { name: "Libreville", country: "Gabon", countryCode: "GA", latitude: 0.4162, longitude: 9.4673, timezone: "Africa/Libreville", region: "africa" },
  // Island nations
  "antananarivo": { name: "Antananarivo", country: "Madagascar", countryCode: "MG", latitude: -18.8792, longitude: 47.5079, timezone: "Indian/Antananarivo", region: "africa" },
  "port-louis": { name: "Port Louis", country: "Mauritius", countryCode: "MU", latitude: -20.1609, longitude: 57.5012, timezone: "Indian/Mauritius", region: "africa" },
  "freetown": { name: "Freetown", country: "Sierra Leone", countryCode: "SL", latitude: 8.4847, longitude: -13.2343, timezone: "Africa/Freetown", region: "africa" },
  "niamey": { name: "Niamey", country: "Niger", countryCode: "NE", latitude: 13.5127, longitude: 2.1128, timezone: "Africa/Niamey", region: "africa" },
  "nouakchott": { name: "Nouakchott", country: "Mauritania", countryCode: "MR", latitude: 18.0735, longitude: -15.9582, timezone: "Africa/Nouakchott", region: "africa" },
  "asmara": { name: "Asmara", country: "Eritrea", countryCode: "ER", latitude: 15.3229, longitude: 38.9251, timezone: "Africa/Asmara", region: "africa" },
  "lilongwe": { name: "Lilongwe", country: "Malawi", countryCode: "MW", latitude: -13.9626, longitude: 33.7741, timezone: "Africa/Blantyre", region: "africa" },
  "victoria-sc": { name: "Victoria", country: "Seychelles", countryCode: "SC", latitude: -4.6191, longitude: 55.4513, timezone: "Indian/Mahe", region: "africa" },
  "praia": { name: "Praia", country: "Cape Verde", countryCode: "CV", latitude: 14.9331, longitude: -23.5133, timezone: "Atlantic/Cape_Verde", region: "africa" },

  // ═══════════════════════════════════════════════════════════════════
  // OCEANIA (~20)
  // ═══════════════════════════════════════════════════════════════════

  // Australia
  "sydney": { name: "Sydney", country: "Australia", countryCode: "AU", latitude: -33.8688, longitude: 151.2093, timezone: "Australia/Sydney", region: "oceania" },
  "melbourne": { name: "Melbourne", country: "Australia", countryCode: "AU", latitude: -37.8136, longitude: 144.9631, timezone: "Australia/Melbourne", region: "oceania" },
  "brisbane": { name: "Brisbane", country: "Australia", countryCode: "AU", latitude: -27.4698, longitude: 153.0251, timezone: "Australia/Brisbane", region: "oceania" },
  "perth": { name: "Perth", country: "Australia", countryCode: "AU", latitude: -31.9505, longitude: 115.8605, timezone: "Australia/Perth", region: "oceania" },
  "adelaide": { name: "Adelaide", country: "Australia", countryCode: "AU", latitude: -34.9285, longitude: 138.6007, timezone: "Australia/Adelaide", region: "oceania" },
  "gold-coast": { name: "Gold Coast", country: "Australia", countryCode: "AU", latitude: -28.0167, longitude: 153.4000, timezone: "Australia/Brisbane", region: "oceania" },
  "canberra": { name: "Canberra", country: "Australia", countryCode: "AU", latitude: -35.2809, longitude: 149.1300, timezone: "Australia/Sydney", region: "oceania" },
  "hobart": { name: "Hobart", country: "Australia", countryCode: "AU", latitude: -42.8821, longitude: 147.3272, timezone: "Australia/Hobart", region: "oceania" },
  "darwin": { name: "Darwin", country: "Australia", countryCode: "AU", latitude: -12.4634, longitude: 130.8456, timezone: "Australia/Darwin", region: "oceania" },
  "cairns": { name: "Cairns", country: "Australia", countryCode: "AU", latitude: -16.9186, longitude: 145.7781, timezone: "Australia/Brisbane", region: "oceania" },
  // New Zealand
  "auckland": { name: "Auckland", country: "New Zealand", countryCode: "NZ", latitude: -36.8485, longitude: 174.7633, timezone: "Pacific/Auckland", region: "oceania" },
  "wellington": { name: "Wellington", country: "New Zealand", countryCode: "NZ", latitude: -41.2865, longitude: 174.7762, timezone: "Pacific/Auckland", region: "oceania" },
  "christchurch": { name: "Christchurch", country: "New Zealand", countryCode: "NZ", latitude: -43.5321, longitude: 172.6362, timezone: "Pacific/Auckland", region: "oceania" },
  "queenstown": { name: "Queenstown", country: "New Zealand", countryCode: "NZ", latitude: -45.0312, longitude: 168.6626, timezone: "Pacific/Auckland", region: "oceania" },
  // Pacific Islands
  "suva": { name: "Suva", country: "Fiji", countryCode: "FJ", latitude: -18.1416, longitude: 178.4419, timezone: "Pacific/Fiji", region: "oceania" },
  "nadi": { name: "Nadi", country: "Fiji", countryCode: "FJ", latitude: -17.7765, longitude: 177.9500, timezone: "Pacific/Fiji", region: "oceania" },
  "port-moresby": { name: "Port Moresby", country: "Papua New Guinea", countryCode: "PG", latitude: -9.4438, longitude: 147.1803, timezone: "Pacific/Port_Moresby", region: "oceania" },
  "apia": { name: "Apia", country: "Samoa", countryCode: "WS", latitude: -13.8333, longitude: -171.7500, timezone: "Pacific/Apia", region: "oceania" },
  "noumea": { name: "Nouméa", country: "New Caledonia", countryCode: "NC", latitude: -22.2558, longitude: 166.4505, timezone: "Pacific/Noumea", region: "oceania" },
  "papeete": { name: "Papeete", country: "French Polynesia", countryCode: "PF", latitude: -17.5516, longitude: -149.5585, timezone: "Pacific/Tahiti", region: "oceania" },
};

export function getCityBySlug(slug: string): CityData | undefined {
  return CITIES[slug];
}

export function getAllCitySlugs(): string[] {
  return Object.keys(CITIES);
}

export function getCityLabel(city: CityData): string {
  return `${city.name}, ${city.country}`;
}

// Convert slug to search query for dynamic geocoding
export function slugToQuery(slug: string): string {
  return slug.replace(/-/g, " ");
}
